language: python
python:
- "3.4"
- "3.12"
install: true
before_install:
  - sudo apt-get install -y vim
  - git config --global user.email "fake@user.com"
  - git config --global user.name "fake user"
script: ./spec.py

