#!/usr/bin/env python

import subprocess
import sys
import re

project = 'EXAMPLE'

issue_pattern = '{}-[\d]+'.format(project)
issue_format = '{}'

try:
    current_ref = subprocess.check_output('git symbolic-ref HEAD', shell=True)
except subprocess.CalledProcessError:
    print("add-issue-id-hook: Adding issue id failed. Are you in detached HEAD state?")
    sys.exit()

current_branch = current_ref[len('refs/heads/'):]

issue_match = re.match(issue_pattern, current_branch)
if issue_match:
    with open(sys.argv[1], 'r') as f:
        original_msg = f.read()
    issue = issue_format.format(issue_match.group())
    if not original_msg.startswith(issue):
        with open(sys.argv[1], 'w') as f:
            f.write('{0} {1}'.format(issue, original_msg))
